name: Laravel

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - name: Run webpack to production
      run: npm run build
